### ISSUE TITLE
Usage with debug/release

### ISSUE THREAD

**Issue by sdebruyn** [marukami/MineCanery#1]
How can I make sure that this doesn't ship in my Release/AppStore builds and that it does ship in my debug builds?

**Comment by mtilbrook-dev** [comment]
With Java Android, Gradle allows your builds to have build specific dependencies. For release, you would use the no-op variant of leakcanary `com.squareup.leakcanary:leakcanary-android-no-op`

Been a while since my last Xamarin project. But I would look at creating a separate binding for the `leakcanary-android-no-op` and swap the DLL's at compile time for each build variant. CAKE should make swapping them simple enough. So, You would still call into the no-op but nothing would happen.

You should be able to modify this CAKE script https://ghuntley.com/archive/2016/07/11/example-of-xamarin-android-with-cake/ maybe split the `Task("Build")` into separate builds. Still new to CAKE.

**Comment by sdebruyn** [comment]
Thanks, that should get me started!
